const data={
    product:[
        {
            _id:'1',
            name:'Raymonds Slim Shirts',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:780,
            countInStock:0,
            brand:'Raymonds',
            rating:5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirts',
            category:'Shirts',
            image:'/images/product-2.jpg',
            price:999,
            countInStock:3,
            brand:'Adidas',
            rating:4.8,
            numReviews:21,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Raymonds Slim Shirts',
            category:'Shirts',
            image:'/images/product-3.jpg',
            price:750,
            countInStock:8,
            brand:'Raymonds',
            rating:4.5,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Raymonds Pant',
            category:'Pants',
            image:'/images/product-4.jpg',
            price:849,
            countInStock:7,
            brand:'Raymonds',
            rating:5,
            numReviews:16,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Nike Slim Fit Pant',
            category:'Pants',
            image:'/images/product-5.jpg',
            price:1149,
            countInStock:2,
            brand:'Nike',
            rating:4.9,
            numReviews:18,
            description:'high quality product',
        },
    ],
};
export default data;